# Generated by Django 3.2.6 on 2021-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='info_dd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
