# Generated by Django 3.2.9 on 2021-12-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_room'),
        ('home', '0005_product_n_orders'),
    ]

    operations = [
    ]
