# Generated by Django 3.2.9 on 2021-12-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_customer_phone_number'),
        ('home', '0009_customer_phone_number'),
    ]

    operations = [
    ]
