# Generated by Django 3.2.9 on 2021-12-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211204_1655'),
        ('home', '0011_auto_20211204_1703'),
    ]

    operations = [
    ]
